[project]
authors = ["Hannah Zafar <hannah.zafar@nasa.gov>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "MERRA2_processing"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.13.*"
numpy = ">=2.3.3,<3"
pandas = ">=2.3.3,<3"
xarray = ">=2025.10.1,<2026"
